"""Core package for NLASM Engine."""

from .aot_codegen import AOTCodeGen
from .aot_compiler import AOTCompiler
from .builtins import BUILTINS, BuiltinRegistry
from .concurrency import AsyncTask, NLASMConcurrency
from .debugger import Breakpoint, DebugAction, DebugEvent, DebugFrame, NLASMDebugger
from .entities import Entity
from .file_parser import NLFileParser, ParseError
from .frontend import Frontend, IntentPacket, RuleEntityExtractor
from .inline_cache import InlineCache, build_cache_key, normalize_type_signature
from .ir import (
    Add,
    And,
    AsyncCall,
    Assign,
    AttributeAccess,
    AwaitExpr,
    Break,
    CallPython,
    ClassDef,
    Cmp,
    Continue,
    DictExpr,
    Div,
    Expr,
    For,
    ForRange,
    FuncCall,
    FuncDef,
    If,
    ImportStmt,
    IndexAccess,
    IRNode,
    ListExpr,
    Literal,
    Loop,
    Match,
    Mod,
    Mul,
    Neg,
    Not,
    Or,
    ParallelCall,
    Print,
    Raise,
    Return,
    Stmt,
    StringConcat,
    Sub,
    TryExcept,
    Var,
    VarDecl,
    While,
)
from .ir_interpreter import IRInterpreter, NLASMClass, NLASMInstance, NLASMMethod
from .ir_pattern import IRPattern
from .module_system import Module, ModuleLoader
from .package_manager import (
    LOCK_FILE,
    MANIFEST_FILE,
    PACKAGES_DIR,
    ConflictInfo,
    DependencyNode,
    DownloadManager,
    GitInstaller,
    LocalRegistry,
    LockEntry,
    LockFile,
    PackageManifest,
    PackageManager,
    PackageRegistry,
    PathInstaller,
    RegistryConfig,
    RegistryManager,
    SemVer,
    VersionRange,
    VersionResolver,
    compute_hash,
    extract_zip,
    is_git_url,
    parse_git_spec,
    verify_integrity,
)
from .pattern_database import PATTERN_DB
from .pattern_instantiator import PatternInstantiator
from .pipeline import PipelineV08
from .profiler import Profiler
from .python_api import NLASMFunction, compile
from .python_bridge import PythonBridge
from .runtime import Runtime
from .semantic_operators import OPERATOR_SEMANTICS, SemanticOperatorMatcher
from .slot_filler import SlotFiller
from .slot_types import ArraySlot, PredicateSlot, ScalarSlot
from .symbol_table import SymbolTable
from .type_system import (
    ANY,
    ArrayType,
    BoolType,
    DictType,
    FloatType,
    FuncType,
    IntType,
    NLType,
    NoneType,
    StrType,
    TypeChecker,
    UnionType,
    infer_type,
    parse_type,
)

__all__ = [
    "ANY",
    "Add",
    "And",
    "AsyncCall",
    "AOTCodeGen",
    "AOTCompiler",
    "ArraySlot",
    "ArrayType",
    "Assign",
    "AsyncTask",
    "AttributeAccess",
    "AwaitExpr",
    "BUILTINS",
    "BoolType",
    "Break",
    "Breakpoint",
    "BuiltinRegistry",
    "CallPython",
    "ClassDef",
    "Cmp",
    "Continue",
    "DebugAction",
    "DebugEvent",
    "DebugFrame",
    "DictExpr",
    "DictType",
    "Div",
    "Entity",
    "Expr",
    "For",
    "ForRange",
    "FloatType",
    "FuncCall",
    "FuncDef",
    "FuncType",
    "Frontend",
    "IRInterpreter",
    "IRNode",
    "IRPattern",
    "If",
    "ImportStmt",
    "IndexAccess",
    "InlineCache",
    "IntentPacket",
    "IntType",
    "ListExpr",
    "Literal",
    "Loop",
    "Match",
    "Mod",
    "Module",
    "ModuleLoader",
    "LocalRegistry",
    "LockEntry",
    "LockFile",
    "LOCK_FILE",
    "MANIFEST_FILE",
    "Mul",
    "NLASMClass",
    "NLASMConcurrency",
    "NLASMDebugger",
    "NLASMFunction",
    "NLASMInstance",
    "NLASMMethod",
    "NLFileParser",
    "NLType",
    "Neg",
    "NoneType",
    "Not",
    "Or",
    "PACKAGES_DIR",
    "PATTERN_DB",
    "ParallelCall",
    "ParseError",
    "PackageManifest",
    "PackageManager",
    "PackageRegistry",
    "PathInstaller",
    "PatternInstantiator",
    "PatternMatcher",
    "PipelineV08",
    "PredicateSlot",
    "Print",
    "Profiler",
    "PythonBridge",
    "Raise",
    "RegistryConfig",
    "RegistryManager",
    "Return",
    "Runtime",
    "OPERATOR_SEMANTICS",
    "ScalarSlot",
    "SemanticOperatorMatcher",
    "SemVer",
    "SlotFiller",
    "Stmt",
    "StrType",
    "StringConcat",
    "Sub",
    "SymbolTable",
    "TryExcept",
    "TypeChecker",
    "UnionType",
    "Var",
    "VarDecl",
    "While",
    "VersionRange",
    "VersionResolver",
    "ConflictInfo",
    "DependencyNode",
    "DownloadManager",
    "GitInstaller",
    "build_cache_key",
    "compile",
    "infer_type",
    "normalize_type_signature",
    "parse_type",
]
